### ISSUE TITLE
Error 52100 after setting up the server

### ISSUE THREAD

**Issue by Real96** [EnergyCube/cowfc_installer#1]
I was able to make the installer script work correctly and after completing installation i'm able to enter the server using my local ip in my browser.
But when i try to connect my DS with a no ssl patched game, i get error 52100.
Am i missing something?
I'm using Ubuntu 16.04 fresh installed

**Comment by EnergyCube** [comment]
Fixed in Discord mp.

The **network adapter** chosen in the Virtual Machine settings was wrong, which made the server inaccessible from the local network.
When this is the case a re-installation is often necessary because the VM IP Address changes.
