### ISSUE TITLE
dsnsmasq error

### ISSUE THREAD

**Issue by Killzalot** [EnergyCube/cowfc_installer#4]
Does anyone know how to fix this error?
when i try - sudo service dnsmasq start
Error: Job for dnsmsaq.service failed because the control process exited with error code.  See systemctl status dnsmasq.service" and "journalctl - xe" for details.

**Comment by Killzalot** [comment]
resolved it by putting enp0s3.

**Comment by EnergyCube** [comment]
Yep, you have to be careful when selecting the network adapter that's important.
