### ISSUE TITLE
Cant get into nintendo online

### ISSUE THREAD

**Issue by Killzalot** [EnergyCube/cowfc_installer#5]
Errors out with default nintendo traffic error code 23918.  I patched game with v3 and setup server correctly as far as I know.  Anyone know why this is happening instead of putting connecting me?

**Comment by barthogenes** [comment]
Are you using the Dolphin emulator on Windows? It is probably trying to connect to the Wiimmfi server instead of your private server.
You can try the fix I posted in [this issue](https://github.com/barronwaffles/dwc_network_server_emulator/issues/546).

**Comment by Killzalot** [comment]
Yes, it keeps erroring out with this error code now. 20100.  I patched the game with v3 of dwc server.  1 thing im not 100% on is if the ip should be same or different for example.  Virtual server ip is 192.168.1.121.  My ethernet LAN adapter IP is 192.168.1.125.  On a side note I have tried both and no luck.

**Comment by EnergyCube** [comment]
Can you specify more information ? The game that you patched, are you running the server on Ubuntu or Debian ? Did you host it in LAN or on a VPS ? With or without domain name ?

**Comment by EnergyCube** [comment]
No news since a month.
Closing issue, if there is any news don't hesitate to open this issue again.
