### ISSUE TITLE
Can't bypass internet check

### ISSUE THREAD

**Issue by D-06** [EnergyCube/cowfc_installer#9]
When i tries install on ubuntu 18.04 and 20.04 it said internet check is failed eventhough i add -s arg line
root@localhost:/var/www# bash cowfc.sh
########## !!!!! WARNING !!!!! ##########
Recently, Wiimmfi has undergone some changes which makes it so that their servers are more secure from hackers.
Having said that, this means that the CoWFC fork will not be getting the security patch, as it is unclear how it is possible. For the time being, you accept that you run your own server with a chance that hackers will be able to execute code over the MKW network.
This might mean that hackers can in theory, brick consoles.
Please type ACCEPT to accept the risk: ACCEPT
Just in case you were trigger-happy, I'll need you to type ACCEPT.: ACCEPT
cowfc.sh: line 40: /dev/nul: Permission denied
cowfc.sh: line 42: /dev/nul: Permission denied
Internet Connection Test Failed!
If you want to bypass internet check use -s arg!
root@localhost:/var/www# bash cowfc.sh -s arg
########## !!!!! WARNING !!!!! ##########
Recently, Wiimmfi has undergone some changes which makes it so that their servers are more secure from hackers.
Having said that, this means that the CoWFC fork will not be getting the security patch, as it is unclear how it is possible. For the time being, you accept that you run your own server with a chance that hackers will be able to execute code over the MKW network.
This might mean that hackers can in theory, brick consoles.
Please type ACCEPT to accept the risk: ACCEPT
Just in case you were trigger-happy, I'll need you to type ACCEPT.: ACCEPT
cowfc.sh: line 40: /dev/nul: Permission denied
cowfc.sh: line 42: /dev/nul: Permission denied
Internet Connection Test Failed!
If you want to bypass internet check use -s arg!
root@localhost:/var/www#

**Comment by GabIsAwesome** [comment]
The same happens to me! D:

**Comment by EnergyCube** [comment]
Strange :O
It would require to add an argument to the script, for the moment you can delete the lines https://github.com/EnergyCube/cowfc_installer/blob/5eb1d145de9d86521d3df01884ec08f80694d3fd/cowfc.sh#L39-L48
It will remove the internet check.
